// Build the source package AMO requires for a bundler-built add-on:
// `node scripts/source-package.mjs`.
//
// AMO's source code submission policy applies to any add-on built with a
// bundler, minified or not, so the Firefox upload always needs this alongside
// it. The package must let a reviewer rebuild dist/firefox/ byte-for-byte, so
// it carries the sources, the build scripts, the lockfile, and AMO_REVIEW.md
// (renamed to README.md, which is where reviewers look for build steps).
import { cpSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = fileURLToPath(new URL('../', import.meta.url));
const staging = join(root, 'dist', 'source');
const archive = join(root, 'skyreader-extension-firefox-source.zip');

rmSync(staging, { recursive: true, force: true });
mkdirSync(staging, { recursive: true });

// Everything needed to reproduce the build, and nothing generated by it:
// no node_modules, no dist/, and no content/extract.js (the build writes it).
for (const file of [
  'manifest.json',
  'background.js',
  'popup.html',
  'popup.js',
  'options.html',
  'options.js',
  'src',
  'icons',
  'scripts',
  'test',
  'package.json',
  'package-lock.json',
  'LICENSE',
]) {
  cpSync(join(root, file), join(staging, file), { recursive: true });
}

// Reviewers look for build instructions in README.md.
cpSync(join(root, 'AMO_REVIEW.md'), join(staging, 'README.md'));

rmSync(archive, { force: true });
execFileSync('zip', ['-r', archive, '.', '-x', '*.DS_Store'], {
  cwd: staging,
  stdio: 'inherit',
});
